-- MySQL Script generated by MySQL Workbench
-- Tue Sep 26 15:49:37 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hrs
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hrs` ;

-- -----------------------------------------------------
-- Schema hrs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hrs` DEFAULT CHARACTER SET utf8 ;
USE `hrs` ;

-- -----------------------------------------------------
-- Table `hrs`.`tb_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrs`.`tb_user` ;

CREATE TABLE IF NOT EXISTS `hrs`.`tb_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrs`.`tb_dept`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrs`.`tb_dept` ;

CREATE TABLE IF NOT EXISTS `hrs`.`tb_dept` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dno` INT NOT NULL,
  `dname` VARCHAR(20) NOT NULL,
  `dloc` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrs`.`tb_emp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrs`.`tb_emp` ;

CREATE TABLE IF NOT EXISTS `hrs`.`tb_emp` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `eno` INT NOT NULL,
  `ename` VARCHAR(20) NOT NULL,
  `esex` BIT NULL DEFAULT 1,
  `ejob` VARCHAR(20) NOT NULL,
  `esal` FLOAT NULL,
  `ehiredate` DATE NULL,
  `estatus` BIT NULL DEFAULT 1,
  `ephoto` VARCHAR(255) NULL,
  `etel` CHAR(11) NULL,
  `tb_dept_id` INT NULL,
  `tb_emp_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_emp_tb_dept_idx` (`tb_dept_id` ASC),
  INDEX `fk_tb_emp_tb_emp1_idx` (`tb_emp_id` ASC),
  CONSTRAINT `fk_tb_emp_tb_dept`
    FOREIGN KEY (`tb_dept_id`)
    REFERENCES `hrs`.`tb_dept` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tb_emp_tb_emp1`
    FOREIGN KEY (`tb_emp_id`)
    REFERENCES `hrs`.`tb_emp` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
